#cloud-config
autoinstall:
  version: 1

  identity:
    realname: ''
    hostname: ubuntu
    username: ubuntu
    password: '$6$wdAcoXrU039hKYPd$508Qvbe7ObUnxoj15DRCkzC3qO7edjH0VV7BPNRDYK4QR8ofJaEEF2heacn0QgD.f8pO8SNp83XNdWG6tocBM1'
  packages:
    - vim
    - bind9-dnsutils
  storage:
    layout:
      name: direct
    swap:
      size: 0
    config:
      - type: partition
        id: boot-partition
        device: root-disk
        size: 10%
      - type: partition
        id: root-partition
        size: 20%
      - type: partition
        id: data-partition
        device: root-disk
        size: 30%
