#cloud-config
autoinstall:
  version: 1

  identity:
    realname: ''
    hostname: ubuntu
    username: ubuntu
    password: '$6$wdAcoXrU039hKYPd$508Qvbe7ObUnxoj15DRCkzC3qO7edjH0VV7BPNRDYK4QR8ofJaEEF2heacn0QgD.f8pO8SNp83XNdWG6tocBM1'
  packages:
    - vim
    - bind9-dnsutils
  storage:
    swap:
      size: 0
    config:
      - {type: disk, ptable: gpt, path: /dev/vda, wipe: superblock, preserve: false, grub_device: true, id: disk-1}
      - {type: partition, device: disk-1, size: 1048576, wipe: superblock, flag: bios_grub, number: 1, preserve: false, id: partition-grub-1}
      - {type: partition, device: disk-1, size: 1073741824, wipe: superblock, number: 2, preserve: false, id: partition-boot-1}
      - {type: partition, device: disk-1, size: 10737418240, wipe: superblock, number: 3, preserve: false, id: partition-system-1}
      - {type: format, fstype: ext4, volume: partition-boot-1, preserve: false, id: format-boot}
      - {type: format, fstype: ext4, volume: partition-system-1, preserve: false, id: format-system}
      - {type: mount, device: format-system, path: /, id: mount-system}
      - {type: mount, device: format-boot, path: /boot, id: mount-boot, options: 'errors=remount-ro'}
